import { ClipboardItem } from './types'

function iso(d: Date): string {
  return d.toISOString().replace('T', ' ').slice(0, 19)
}

function ago(ms: number): string {
  return iso(new Date(Date.now() - ms))
}

export const mockItems: ClipboardItem[] = [
  {
    id: 1,
    type: 'text',
    content: '今天天气真不错，适合出去走走。阳光明媚，微风不燥，是个爬山的好日子。',
    preview: '今天天气真不错，适合出去走走。阳光明媚，微风不燥，是个爬山的好日子。',
    char_count: 35,
    storage_size: 105,
    created_at: ago(1000 * 60 * 5),
    is_pinned: false,
    alias: '',
    tags: [],
    is_sensitive: false,
  },
  {
    id: 2,
    type: 'image',
    content: '',
    preview: '图片 1920×1080',
    char_count: 0,
    storage_size: 245760,
    created_at: ago(1000 * 60 * 30),
    is_pinned: true,
    alias: '设计稿截图',
    tags: ['设计'],
    is_sensitive: false,
  },
  {
    id: 3,
    type: 'url',
    content: 'https://github.com/tauri-apps/tauri',
    preview: 'https://github.com/tauri-apps/tauri',
    char_count: 34,
    storage_size: 102,
    created_at: ago(1000 * 60 * 120),
    is_pinned: true,
    alias: 'Tauri 仓库',
    tags: ['代码', '链接'],
    is_sensitive: false,
  },
  {
    id: 4,
    type: 'text',
    content: '剪贴板管理工具 v1.0 开发计划\n\n1. 项目初始化\n2. UI 布局搭建\n3. 剪贴板监听\n4. 数据持久化\n5. 快捷键绑定',
    preview: '剪贴板管理工具 v1.0 开发计划\n\n1. 项目初始化\n2. UI 布局搭建\n3. 剪贴板监听\n4. 数据持久化\n5. 快捷键...',
    char_count: 68,
    storage_size: 204,
    created_at: ago(1000 * 60 * 60 * 5),
    is_pinned: false,
    alias: '',
    tags: [],
    is_sensitive: false,
  },
  {
    id: 5,
    type: 'url',
    content: 'https://www.typescriptlang.org/docs/handbook/',
    preview: 'https://www.typescriptlang.org/docs/handbook/',
    char_count: 47,
    storage_size: 141,
    created_at: ago(1000 * 60 * 60 * 8),
    is_pinned: false,
    alias: '',
    tags: [],
    is_sensitive: false,
  },
  {
    id: 6,
    type: 'text',
    content: 'React 19 新特性：\n- React Compiler (自动记忆化)\n- Server Components 稳定版\n- Actions 与 useActionState\n- Document Metadata 支持\n- Web Components 改进',
    preview: 'React 19 新特性：\n- React Compiler (自动记忆化)\n- Server Components 稳定版\n- Actions 与 useActionState\n- Document Metadata 支持\n- Web Components 改进',
    char_count: 126,
    storage_size: 378,
    created_at: ago(86400000),
    is_pinned: false,
    alias: '',
    tags: [],
    is_sensitive: false,
  },
  {
    id: 7,
    type: 'text',
    content: 'const fibonacci = (n: number): number => {\n  if (n <= 1) return n\n  return fibonacci(n - 1) + fibonacci(n - 2)\n}',
    preview: 'const fibonacci = (n: number): number => {\n  if (n <= 1) return n\n  return fibonacci(n - 1) + fibonacci(n - 2)\n}',
    char_count: 104,
    storage_size: 312,
    created_at: ago(86400000 * 2),
    is_pinned: true,
    alias: '斐波那契函数',
    tags: ['代码'],
    is_sensitive: false,
  },
  {
    id: 8,
    type: 'url',
    content: 'https://tailwindcss.com/docs/installation',
    preview: 'https://tailwindcss.com/docs/installation',
    char_count: 42,
    storage_size: 126,
    created_at: ago(86400000 * 3),
    is_pinned: false,
    alias: '',
    tags: [],
    is_sensitive: false,
  },
  {
    id: 9,
    type: 'image',
    content: '',
    preview: '图片 2560×1440',
    char_count: 0,
    storage_size: 524288,
    created_at: ago(86400000 * 5),
    is_pinned: false,
    alias: '',
    tags: [],
    is_sensitive: false,
  },
  {
    id: 10,
    type: 'text',
    content: '向后端请求 API 时务必带上 Authorization header，并在 401 时自动刷新 token。',
    preview: '向后端请求 API 时务必带上 Authorization header，并在 401 时自动刷新 token。',
    char_count: 46,
    storage_size: 138,
    created_at: ago(86400000 * 8),
    is_pinned: false,
    alias: '',
    tags: [],
    is_sensitive: false,
  },
  {
    id: 11,
    type: 'url',
    content: 'https://react.dev/reference/react/useCallback',
    preview: 'https://react.dev/reference/react/useCallback',
    char_count: 48,
    storage_size: 144,
    created_at: ago(86400000 * 11),
    is_pinned: false,
    alias: '',
    tags: [],
    is_sensitive: false,
  },
  {
    id: 12,
    type: 'text',
    content: 'sk-proj-abc123def456ghi789jkl012mno345pqr',
    preview: 'sk-proj-abc123def456ghi789jkl012mno345pqr',
    char_count: 42,
    storage_size: 126,
    created_at: ago(86400000 * 13),
    is_pinned: true,
    alias: 'OpenAI API Key',
    tags: ['账号', '敏感'],
    is_sensitive: true,
  },
  {
    id: 13,
    type: 'text',
    content: 'api_key: sk-ant-api03-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    preview: 'api_key: sk-ant-api03-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    char_count: 58,
    storage_size: 174,
    created_at: ago(86400000 * 15),
    is_pinned: false,
    alias: '',
    tags: [],
    is_sensitive: false,
  },
]
